[2024-04-08T01:44:50.270+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_fetch_pipeline.fetch_data_file_0 manual__2024-04-07T20:14:04.452502+00:00 [queued]>
[2024-04-08T01:44:50.278+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_fetch_pipeline.fetch_data_file_0 manual__2024-04-07T20:14:04.452502+00:00 [queued]>
[2024-04-08T01:44:50.279+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-08T01:44:50.299+0530] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_data_file_0> on 2024-04-07 20:14:04.452502+00:00
[2024-04-08T01:44:50.305+0530] {standard_task_runner.py:60} INFO - Started process 78625 to run task
[2024-04-08T01:44:50.309+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'data_fetch_pipeline', 'fetch_data_file_0', 'manual__2024-04-07T20:14:04.452502+00:00', '--job-id', '281', '--raw', '--subdir', 'DAGS_FOLDER/data_fetch_pipeline.py', '--cfg-path', '/tmp/tmpb7dprjwx']
[2024-04-08T01:44:50.312+0530] {standard_task_runner.py:88} INFO - Job 281: Subtask fetch_data_file_0
[2024-04-08T01:44:50.356+0530] {task_command.py:423} INFO - Running <TaskInstance: data_fetch_pipeline.fetch_data_file_0 manual__2024-04-07T20:14:04.452502+00:00 [running]> on host LAPTOP-HO799B2R.
[2024-04-08T01:44:50.436+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_fetch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_data_file_0' AIRFLOW_CTX_EXECUTION_DATE='2024-04-07T20:14:04.452502+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-07T20:14:04.452502+00:00'
[2024-04-08T01:44:50.437+0530] {data_fetch_pipeline.py:84} ERROR - Error fetching data file 0 for year 2022: '<=' not supported between instances of 'int' and 'str'
[2024-04-08T01:44:50.438+0530] {python.py:201} INFO - Done. Returned value was: None
[2024-04-08T01:44:50.442+0530] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=data_fetch_pipeline, task_id=fetch_data_file_0, execution_date=20240407T201404, start_date=20240407T201450, end_date=20240407T201450
[2024-04-08T01:44:50.482+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T01:44:50.508+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
