[2024-04-08T01:45:58.530+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_fetch_pipeline.move_archive manual__2024-04-07T20:14:04.452502+00:00 [queued]>
[2024-04-08T01:45:58.541+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_fetch_pipeline.move_archive manual__2024-04-07T20:14:04.452502+00:00 [queued]>
[2024-04-08T01:45:58.541+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-08T01:45:58.561+0530] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): move_archive> on 2024-04-07 20:14:04.452502+00:00
[2024-04-08T01:45:58.568+0530] {standard_task_runner.py:60} INFO - Started process 79779 to run task
[2024-04-08T01:45:58.571+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'data_fetch_pipeline', 'move_archive', 'manual__2024-04-07T20:14:04.452502+00:00', '--job-id', '292', '--raw', '--subdir', 'DAGS_FOLDER/data_fetch_pipeline.py', '--cfg-path', '/tmp/tmpkcdgpkvk']
[2024-04-08T01:45:58.573+0530] {standard_task_runner.py:88} INFO - Job 292: Subtask move_archive
[2024-04-08T01:45:58.612+0530] {task_command.py:423} INFO - Running <TaskInstance: data_fetch_pipeline.move_archive manual__2024-04-07T20:14:04.452502+00:00 [running]> on host LAPTOP-HO799B2R.
[2024-04-08T01:45:58.691+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_fetch_pipeline' AIRFLOW_CTX_TASK_ID='move_archive' AIRFLOW_CTX_EXECUTION_DATE='2024-04-07T20:14:04.452502+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-07T20:14:04.452502+00:00'
[2024-04-08T01:45:58.694+0530] {data_fetch_pipeline.py:121} ERROR - Error moving archive to //wsl.localhost/Ubuntu/home/lucky/Assign2: Destination directory does not exist.
[2024-04-08T01:45:58.695+0530] {python.py:201} INFO - Done. Returned value was: None
[2024-04-08T01:45:58.707+0530] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=data_fetch_pipeline, task_id=move_archive, execution_date=20240407T201404, start_date=20240407T201558, end_date=20240407T201558
[2024-04-08T01:45:58.786+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T01:45:58.818+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
