[2024-04-08T01:09:08.606+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: data_fetch_pipeline.fetch_data_file_4 manual__2024-04-07T19:02:02+00:00 [queued]>
[2024-04-08T01:09:08.616+0530] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: data_fetch_pipeline.fetch_data_file_4 manual__2024-04-07T19:02:02+00:00 [queued]>
[2024-04-08T01:09:08.617+0530] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2024-04-08T01:09:08.635+0530] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_data_file_4> on 2024-04-07 19:02:02+00:00
[2024-04-08T01:09:08.643+0530] {standard_task_runner.py:60} INFO - Started process 45964 to run task
[2024-04-08T01:09:08.646+0530] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'data_fetch_pipeline', 'fetch_data_file_4', 'manual__2024-04-07T19:02:02+00:00', '--job-id', '147', '--raw', '--subdir', 'DAGS_FOLDER/data_fetch_pipeline.py', '--cfg-path', '/tmp/tmp_nblnb5f']
[2024-04-08T01:09:08.648+0530] {standard_task_runner.py:88} INFO - Job 147: Subtask fetch_data_file_4
[2024-04-08T01:09:08.691+0530] {task_command.py:423} INFO - Running <TaskInstance: data_fetch_pipeline.fetch_data_file_4 manual__2024-04-07T19:02:02+00:00 [running]> on host LAPTOP-HO799B2R.
[2024-04-08T01:09:08.760+0530] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='data_fetch_pipeline' AIRFLOW_CTX_TASK_ID='fetch_data_file_4' AIRFLOW_CTX_EXECUTION_DATE='2024-04-07T19:02:02+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-04-07T19:02:02+00:00'
[2024-04-08T01:09:08.762+0530] {data_fetch_pipeline.py:84} ERROR - Error fetching data file 4 for year 2022: '<=' not supported between instances of 'int' and 'str'
[2024-04-08T01:09:08.763+0530] {python.py:201} INFO - Done. Returned value was: None
[2024-04-08T01:09:08.770+0530] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=data_fetch_pipeline, task_id=fetch_data_file_4, execution_date=20240407T190202, start_date=20240407T193908, end_date=20240407T193908
[2024-04-08T01:09:08.820+0530] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-04-08T01:09:08.846+0530] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
